// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.Api.Datos;

namespace Sistema.Api.Migrations
{
    [DbContext(typeof(DbContextSistema))]
    partial class DbContextSistemaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Sistema.Api.Entidades.Almacen.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 483, DateTimeKind.Local).AddTicks(3530),
                            Descripcion = "Celulares nuevos y usados.",
                            Estado = true,
                            Nombre = "Celulares",
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 488, DateTimeKind.Local).AddTicks(2280)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 488, DateTimeKind.Local).AddTicks(2771),
                            Descripcion = "Tenemos computadoras de ultima generacion.",
                            Estado = true,
                            Nombre = "Computadoras",
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 488, DateTimeKind.Local).AddTicks(2787)
                        });
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Almacen.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 490, DateTimeKind.Local).AddTicks(9515),
                            Nombre = "Dell"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 490, DateTimeKind.Local).AddTicks(9983),
                            Nombre = "Acer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 491, DateTimeKind.Local).AddTicks(5),
                            Nombre = "BLU"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 491, DateTimeKind.Local).AddTicks(8),
                            Nombre = "Asus"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 491, DateTimeKind.Local).AddTicks(11),
                            Nombre = "Google"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 491, DateTimeKind.Local).AddTicks(13),
                            Nombre = "Huawei"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 491, DateTimeKind.Local).AddTicks(15),
                            Nombre = "Apple"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 491, DateTimeKind.Local).AddTicks(18),
                            Nombre = "LG"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 491, DateTimeKind.Local).AddTicks(20),
                            Nombre = "Samsung"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 491, DateTimeKind.Local).AddTicks(22),
                            Nombre = "HP"
                        });
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Almacen.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(685),
                            Descripcion = "Dell Latitude E6540 – Full HD – Core i5 4th Gen – 16GB RAM – 500GB – Teclado Numérico",
                            Estado = true,
                            MarcaId = 1,
                            Nombre = "Laptop Dell Latitude E6540",
                            Precio = 30000.00m,
                            Stock = 15,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(329)
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1119),
                            Descripcion = "LAPTOP ACER PREDATOR CORE I7",
                            Estado = true,
                            MarcaId = 2,
                            Nombre = "LAPTOP ACER PREDATOR",
                            Precio = 44000.00m,
                            Stock = 5,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1102)
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1141),
                            Estado = true,
                            MarcaId = 3,
                            Nombre = "BLU G70",
                            Precio = 7000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1138)
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1145),
                            Descripcion = "Laptop Asus Q301L – Intel Core i5 - 4200u – 8GB RAM – 500GB – Pantalla Touch – Teclado Iluminado – Ultra Liviana",
                            Estado = true,
                            MarcaId = 4,
                            Nombre = "Laptop Asus Q301L",
                            Precio = 25000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1143)
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1150),
                            Descripcion = "LAPTOP DELL G3 15 3579 8va GENERACION",
                            Estado = true,
                            MarcaId = 1,
                            Nombre = "LAPTOP DELL G3 15 3579",
                            Precio = 45000.00m,
                            Stock = 15,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1148)
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1155),
                            Descripcion = "Laptop DELL Inspiron 14-3459 – Intel Core i5-6200U Sexta Gen – 6GB RAM – 500GB HDD – AMD Radeon R5",
                            Estado = true,
                            MarcaId = 1,
                            Nombre = "Laptop DELL Inspiron 14-3459",
                            Precio = 29000.00m,
                            Stock = 20,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1153)
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1159),
                            Estado = true,
                            MarcaId = 5,
                            Nombre = "Google Pixel 4",
                            Precio = 10000.00m,
                            Stock = 12,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1158)
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1164),
                            Estado = true,
                            MarcaId = 6,
                            Nombre = "Huawei Honor 20",
                            Precio = 15000.00m,
                            Stock = 14,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1162)
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1168),
                            Descripcion = "LAPTOP DELL INSPIRON 15 SILVER",
                            Estado = true,
                            MarcaId = 1,
                            Nombre = "LAPTOP DELL INSPIRON 15",
                            Precio = 35000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1166)
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1172),
                            Descripcion = "Laptop DELL INSPIRON 15-3558 – Intel Core i3 Quinta Generación – 4GB RAM – 1TB HDD",
                            Estado = true,
                            MarcaId = 1,
                            Nombre = "Laptop DELL INSPIRON 15-3558",
                            Precio = 40000.00m,
                            Stock = 16,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1170)
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1176),
                            Descripcion = "Laptop Dell Latitude 3350 – Intel Core I5 Quinta Generacion 500GB - 6GB RAM",
                            Estado = true,
                            MarcaId = 1,
                            Nombre = "Laptop Dell Latitude 3350",
                            Precio = 30000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1174)
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1180),
                            Descripcion = "Laptop Dell Latitude E5450 – i5 Quinta Generación – 8GB RAM – 500GB HDD",
                            Estado = true,
                            MarcaId = 1,
                            Nombre = "Laptop Dell Latitude E5450",
                            Precio = 25000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1179)
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1184),
                            Estado = true,
                            MarcaId = 6,
                            Nombre = "Huawei Y7p",
                            Precio = 13000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1183)
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1189),
                            Descripcion = "Laptop Dell Ultrabook E7240 – 12GB Ram – Intel Core i5 – 128GB SSD",
                            Estado = true,
                            MarcaId = 1,
                            Nombre = "Laptop Dell Ultrabook E7240",
                            Precio = 50000.00m,
                            Stock = 15,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1187)
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1193),
                            Descripcion = "Laptop HP 15-ba051wm – Pantalla Touch – Quad-Core A10-9600P – 8GB RAM – 1TB HDD",
                            Estado = true,
                            MarcaId = 10,
                            Nombre = "Laptop HP 15-ba051wm",
                            Precio = 40000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1191)
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1219),
                            Estado = true,
                            MarcaId = 7,
                            Nombre = "iPhone 11 (128GB)",
                            Precio = 86000.00m,
                            Stock = 20,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1217)
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1223),
                            Estado = true,
                            MarcaId = 7,
                            Nombre = "iPhone 8 Plus 64GB",
                            Precio = 20000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1221)
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1227),
                            Descripcion = "Laptop HP 15-f387wm – AMD A8-7410 – 500GB HDD – 4GB RAM – Radeon R5 – Pantalla Táctil – Teclado Numérico",
                            Estado = true,
                            MarcaId = 10,
                            Nombre = "Laptop HP 15-f387wm",
                            Precio = 40000.00m,
                            Stock = 15,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1226)
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1231),
                            Estado = true,
                            MarcaId = 8,
                            Nombre = "LG Aristo 5",
                            Precio = 15000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1230)
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1236),
                            Estado = true,
                            MarcaId = 9,
                            Nombre = "Samsung Galaxy A11",
                            Precio = 25000.00m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 494, DateTimeKind.Local).AddTicks(1234)
                        });
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Almacen.ProductoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsPrincipal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoFotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(3325),
                            FotoPublicId = "Sistema-Ventas/Laptops/Dell%20Latitude%20E6540%20%E2%80%93%20Full%20HD%20%E2%80%93%20Core%20i5%204th%20Gen%20%E2%80%93%2016GB%20RAM%20%E2%80%93%20500GB%20%E2%80%93%20Teclado%20Num%C3%A9rico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Num%C3%A9rico_6540h7hdell2_uckxvb.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816981/Sistema-Ventas/Laptops/Dell Latitude E6540 – Full HD – Core i5 4th Gen – 16GB RAM – 500GB – Teclado Numérico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Numérico_6540h7hdell2_uckxvb.jpg",
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(4751),
                            FotoPublicId = "Sistema-Ventas/Laptops/Dell%20Latitude%20E6540%20%E2%80%93%20Full%20HD%20%E2%80%93%20Core%20i5%204th%20Gen%20%E2%80%93%2016GB%20RAM%20%E2%80%93%20500GB%20%E2%80%93%20Teclado%20Num%C3%A9rico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Num%C3%A9rico_346540h7hdell_snunj0.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816982/Sistema-Ventas/Laptops/Dell Latitude E6540 – Full HD – Core i5 4th Gen – 16GB RAM – 500GB – Teclado Numérico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Numérico_346540h7hdell_snunj0.jpg",
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(4990),
                            FotoPublicId = "Sistema-Ventas/Laptops/Dell%20Latitude%20E6540%20%E2%80%93%20Full%20HD%20%E2%80%93%20Core%20i5%204th%20Gen%20%E2%80%93%2016GB%20RAM%20%E2%80%93%20500GB%20%E2%80%93%20Teclado%20Num%C3%A9rico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Num%C3%A9rico_16540h7hdell_dhnsn9.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816981/Sistema-Ventas/Laptops/Dell Latitude E6540 – Full HD – Core i5 4th Gen – 16GB RAM – 500GB – Teclado Numérico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Numérico_16540h7hdell_dhnsn9.jpg",
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5141),
                            FotoPublicId = "Sistema-Ventas/Laptops/Dell%20Latitude%20E6540%20%E2%80%93%20Full%20HD%20%E2%80%93%20Core%20i5%204th%20Gen%20%E2%80%93%2016GB%20RAM%20%E2%80%93%20500GB%20%E2%80%93%20Teclado%20Num%C3%A9rico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Num%C3%A9rico_776540h7hdell_kwtv8a.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816981/Sistema-Ventas/Laptops/Dell Latitude E6540 – Full HD – Core i5 4th Gen – 16GB RAM – 500GB – Teclado Numérico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Numérico_776540h7hdell_kwtv8a.jpg",
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5294),
                            FotoPublicId = "Sistema-Ventas/Laptops/Dell%20Latitude%20E6540%20%E2%80%93%20Full%20HD%20%E2%80%93%20Core%20i5%204th%20Gen%20%E2%80%93%2016GB%20RAM%20%E2%80%93%20500GB%20%E2%80%93%20Teclado%20Num%C3%A9rico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Num%C3%A9rico_566540h7hdell_yhzsr4.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816981/Sistema-Ventas/Laptops/Dell Latitude E6540 – Full HD – Core i5 4th Gen – 16GB RAM – 500GB – Teclado Numérico/Dell_Latitude_E6540_Full_HD_Core_i5_4th_Gen_16GB_RAM_500GB_Teclado_Numérico_566540h7hdell_yhzsr4.jpg",
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5566),
                            FotoPublicId = "Sistema-Ventas/Laptops/LAPTOP%20ACER%20PREDATOR%20CORE%20I7/LAPTOP_ACER_PREDATOR_CORE_I7_laptop-gamer-acer-predator-helios-300-i7-9750h-gtx-ti-6gb-D_NQ_NP_853948-MPE32067580368_092019-F-scaled_uldpur.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816982/Sistema-Ventas/Laptops/LAPTOP ACER PREDATOR CORE I7/LAPTOP_ACER_PREDATOR_CORE_I7_laptop-gamer-acer-predator-helios-300-i7-9750h-gtx-ti-6gb-D_NQ_NP_853948-MPE32067580368_092019-F-scaled_uldpur.jpg",
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5594),
                            FotoPublicId = "Sistema-Ventas/Laptops/LAPTOP%20ACER%20PREDATOR%20CORE%20I7/LAPTOP_ACER_PREDATOR_CORE_I7_laptop-acer-predator-helios-300-i7-8va-gtx-1060-16gb-ram-D_NQ_NP_816622-MPE32377868369_092019-F-scaled_wmhgav.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816981/Sistema-Ventas/Laptops/LAPTOP ACER PREDATOR CORE I7/LAPTOP_ACER_PREDATOR_CORE_I7_laptop-acer-predator-helios-300-i7-8va-gtx-1060-16gb-ram-D_NQ_NP_816622-MPE32377868369_092019-F-scaled_wmhgav.jpg",
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5613),
                            FotoPublicId = "Sistema-Ventas/Celulares/BLU%20G70/BLU_G70_Precio-BLU-G70-en-Costa-Rica_pynkr4.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816936/Sistema-Ventas/Celulares/BLU G70/BLU_G70_Precio-BLU-G70-en-Costa-Rica_pynkr4.jpg",
                            ProductoId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5632),
                            FotoPublicId = "Sistema-Ventas/Celulares/BLU%20G70/BLU_G70_BLU-G70-en-Costa-Rica-433x559_t05hzt.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816935/Sistema-Ventas/Celulares/BLU G70/BLU_G70_BLU-G70-en-Costa-Rica-433x559_t05hzt.jpg",
                            ProductoId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5649),
                            FotoPublicId = "Sistema-Ventas/Celulares/BLU%20G70/BLU_G70_Comprar-BLU-G70-en-Costa-Rica-491x1024_o0bsan.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816935/Sistema-Ventas/Celulares/BLU G70/BLU_G70_Comprar-BLU-G70-en-Costa-Rica-491x1024_o0bsan.jpg",
                            ProductoId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5824),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20Asus%20Q301L%20%E2%80%93%20Intel%20Core%20i5-4200u%20%E2%80%93%208GB%20RAM%20%E2%80%93%20500GB%20%E2%80%93%20Pantalla%20Touch%20%E2%80%93%20Teclado%20Iluminado%20%E2%80%93%20Ultra%20Liviana/Laptop_Asus_Q301L_Intel_Core_i5-4200u_8GB_RAM_500GB_Pantalla_Touch_Teclado_Iluminado_Ultra_Liviana_asus1_qk5rzi.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816981/Sistema-Ventas/Laptops/Laptop Asus Q301L – Intel Core i5-4200u – 8GB RAM – 500GB – Pantalla Touch – Teclado Iluminado – Ultra Liviana/Laptop_Asus_Q301L_Intel_Core_i5-4200u_8GB_RAM_500GB_Pantalla_Touch_Teclado_Iluminado_Ultra_Liviana_asus1_qk5rzi.jpg",
                            ProductoId = 4
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5849),
                            FotoPublicId = "Sistema-Ventas/Laptops/LAPTOP%20DELL%20G3%2015%203579%208Then%20GENERATION/LAPTOP_DELL_G3_15_3579_8Then_GENERATION_notebook-dell-g3-15-3579-156-intel-core-i7-8750h-220-ghz-8gb-ddr4-scaled_gsysxu.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816982/Sistema-Ventas/Laptops/LAPTOP DELL G3 15 3579 8Then GENERATION/LAPTOP_DELL_G3_15_3579_8Then_GENERATION_notebook-dell-g3-15-3579-156-intel-core-i7-8750h-220-ghz-8gb-ddr4-scaled_gsysxu.jpg",
                            ProductoId = 5
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5871),
                            FotoPublicId = "Sistema-Ventas/Laptops/LAPTOP%20DELL%20G3%2015%203579%208Then%20GENERATION/LAPTOP_DELL_G3_15_3579_8Then_GENERATION_laptop-dell-g3-3579-15-i5-8300h-video-4gb-1tb-8gb-p-D_NQ_NP_621638-MPE32062793856_092019-F-scaled_zvmdzz.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816982/Sistema-Ventas/Laptops/LAPTOP DELL G3 15 3579 8Then GENERATION/LAPTOP_DELL_G3_15_3579_8Then_GENERATION_laptop-dell-g3-3579-15-i5-8300h-video-4gb-1tb-8gb-p-D_NQ_NP_621638-MPE32062793856_092019-F-scaled_zvmdzz.jpg",
                            ProductoId = 5
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(5891),
                            FotoPublicId = "Sistema-Ventas/Laptops/LAPTOP%20DELL%20G3%2015%203579%208Then%20GENERATION/LAPTOP_DELL_G3_15_3579_8Then_GENERATION_1-34-scaled_e4mqob.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816982/Sistema-Ventas/Laptops/LAPTOP DELL G3 15 3579 8Then GENERATION/LAPTOP_DELL_G3_15_3579_8Then_GENERATION_1-34-scaled_e4mqob.jpg",
                            ProductoId = 5
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6051),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20DELL%20Inspiron%2014-3459%20%E2%80%93%20Intel%20Core%20i5-6200U%20Sexta%20Gen%20%E2%80%93%206GB%20RAM%20%E2%80%93%20500GB%20HDD%20%E2%80%93%20AMD%20Radeon%20R5/Laptop_DELL_Inspiron_14-3459_Intel_Core_i5-6200U_Sexta_Gen_6GB_RAM_500GB_HDD_AMD_Radeon_R5_107607_71Tri1yZUCL_SL1500__i7j57w.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816982/Sistema-Ventas/Laptops/Laptop DELL Inspiron 14-3459 – Intel Core i5-6200U Sexta Gen – 6GB RAM – 500GB HDD – AMD Radeon R5/Laptop_DELL_Inspiron_14-3459_Intel_Core_i5-6200U_Sexta_Gen_6GB_RAM_500GB_HDD_AMD_Radeon_R5_107607_71Tri1yZUCL_SL1500__i7j57w.jpg",
                            ProductoId = 6
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6070),
                            FotoPublicId = "Sistema-Ventas/Celulares/Google%20Pixel%204/Google_Pixel_4_51jjGHHKixL._AC_SX425__dxkxdc.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816945/Sistema-Ventas/Celulares/Google Pixel 4/Google_Pixel_4_51jjGHHKixL._AC_SX425__dxkxdc.jpg",
                            ProductoId = 7
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6086),
                            FotoPublicId = "Sistema-Ventas/Celulares/Google%20Pixel%204/Google_Pixel_4_149597-phones-news-this-is-the-google-pixel-4-xl-image1-ktsr2yozg6_dpm6jk.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816944/Sistema-Ventas/Celulares/Google Pixel 4/Google_Pixel_4_149597-phones-news-this-is-the-google-pixel-4-xl-image1-ktsr2yozg6_dpm6jk.jpg",
                            ProductoId = 7
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6100),
                            FotoPublicId = "Sistema-Ventas/Celulares/Google%20Pixel%204/Google_Pixel_4_1366_2000_foaiqs.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816944/Sistema-Ventas/Celulares/Google Pixel 4/Google_Pixel_4_1366_2000_foaiqs.jpg",
                            ProductoId = 7
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6118),
                            FotoPublicId = "Sistema-Ventas/Celulares/Huawei%20Honor%2020/Huawei_Honor_20_GKK-Detachable-Case-for-Huawei-Honor-20-Black-10072019-01-p_few99o.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816945/Sistema-Ventas/Celulares/Huawei Honor 20/Huawei_Honor_20_GKK-Detachable-Case-for-Huawei-Honor-20-Black-10072019-01-p_few99o.jpg",
                            ProductoId = 8
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6131),
                            FotoPublicId = "Sistema-Ventas/Celulares/Huawei%20Honor%2020/Huawei_Honor_20_ef6g5t8x0aioqpg_cucvyh.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816944/Sistema-Ventas/Celulares/Huawei Honor 20/Huawei_Honor_20_ef6g5t8x0aioqpg_cucvyh.jpg",
                            ProductoId = 8
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6149),
                            FotoPublicId = "Sistema-Ventas/Celulares/Huawei%20Honor%2020/Huawei_Honor_20_funda_de_silicona_huawei_honor_20_02_transparente_ad_l_uyu1kx.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816944/Sistema-Ventas/Celulares/Huawei Honor 20/Huawei_Honor_20_funda_de_silicona_huawei_honor_20_02_transparente_ad_l_uyu1kx.jpg",
                            ProductoId = 8
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6168),
                            FotoPublicId = "Sistema-Ventas/Laptops/LAPTOP%20DELL%20INSPIRON%2015%20SILVER/LAPTOP_DELL_INSPIRON_15_SILVER_notebook-dell-inspiron-15-5000-156-fhd-intel-core-i5-825-D_NQ_NP_967204-MPE32061439156_092019-F-scaled_eitw4k.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816983/Sistema-Ventas/Laptops/LAPTOP DELL INSPIRON 15 SILVER/LAPTOP_DELL_INSPIRON_15_SILVER_notebook-dell-inspiron-15-5000-156-fhd-intel-core-i5-825-D_NQ_NP_967204-MPE32061439156_092019-F-scaled_eitw4k.jpg",
                            ProductoId = 9
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6187),
                            FotoPublicId = "Sistema-Ventas/Laptops/LAPTOP%20DELL%20INSPIRON%2015%20SILVER/LAPTOP_DELL_INSPIRON_15_SILVER_notebook-dell-inspiron-15-5000-15-5570-156-core-i5-68fnp-D_NQ_NP_781655-MPE32061793687_092019-F-scaled_alicmc.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816983/Sistema-Ventas/Laptops/LAPTOP DELL INSPIRON 15 SILVER/LAPTOP_DELL_INSPIRON_15_SILVER_notebook-dell-inspiron-15-5000-15-5570-156-core-i5-68fnp-D_NQ_NP_781655-MPE32061793687_092019-F-scaled_alicmc.jpg",
                            ProductoId = 9
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6204),
                            FotoPublicId = "Sistema-Ventas/Laptops/LAPTOP%20DELL%20INSPIRON%2015%20SILVER/LAPTOP_DELL_INSPIRON_15_SILVER_notebook-dell-inspiron-15-3581-156-fhd-intel-core-i3-7020-D_NQ_NP_660749-MPE31598311513_072019-F-scaled_yrnlhi.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816982/Sistema-Ventas/Laptops/LAPTOP DELL INSPIRON 15 SILVER/LAPTOP_DELL_INSPIRON_15_SILVER_notebook-dell-inspiron-15-3581-156-fhd-intel-core-i3-7020-D_NQ_NP_660749-MPE31598311513_072019-F-scaled_yrnlhi.jpg",
                            ProductoId = 9
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6339),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20DELL%20INSPIRON%2015-3558%20%E2%80%93%20Intel%20Core%20i3%20Quinta%20Generaci%C3%B3n%20%E2%80%93%204GB%20RAM%20%E2%80%93%201TB%20HDD/Laptop_DELL_INSPIRON_15-3558_Intel_Core_i3_Quinta_Generaci%C3%B3n_4GB_RAM_1TB_HDD_43558dell36689-1_cjqhsy.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816983/Sistema-Ventas/Laptops/Laptop DELL INSPIRON 15-3558 – Intel Core i3 Quinta Generación – 4GB RAM – 1TB HDD/Laptop_DELL_INSPIRON_15-3558_Intel_Core_i3_Quinta_Generación_4GB_RAM_1TB_HDD_43558dell36689-1_cjqhsy.jpg",
                            ProductoId = 10
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6486),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20DELL%20INSPIRON%2015-3558%20%E2%80%93%20Intel%20Core%20i3%20Quinta%20Generaci%C3%B3n%20%E2%80%93%204GB%20RAM%20%E2%80%93%201TB%20HDD/Laptop_DELL_INSPIRON_15-3558_Intel_Core_i3_Quinta_Generaci%C3%B3n_4GB_RAM_1TB_HDD_3558dell36689_ostn27.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816983/Sistema-Ventas/Laptops/Laptop DELL INSPIRON 15-3558 – Intel Core i3 Quinta Generación – 4GB RAM – 1TB HDD/Laptop_DELL_INSPIRON_15-3558_Intel_Core_i3_Quinta_Generación_4GB_RAM_1TB_HDD_3558dell36689_ostn27.jpg",
                            ProductoId = 10
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6619),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20DELL%20INSPIRON%2015-3558%20%E2%80%93%20Intel%20Core%20i3%20Quinta%20Generaci%C3%B3n%20%E2%80%93%204GB%20RAM%20%E2%80%93%201TB%20HDD/Laptop_DELL_INSPIRON_15-3558_Intel_Core_i3_Quinta_Generaci%C3%B3n_4GB_RAM_1TB_HDD_23558dell36689_wxdxod.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816983/Sistema-Ventas/Laptops/Laptop DELL INSPIRON 15-3558 – Intel Core i3 Quinta Generación – 4GB RAM – 1TB HDD/Laptop_DELL_INSPIRON_15-3558_Intel_Core_i3_Quinta_Generación_4GB_RAM_1TB_HDD_23558dell36689_wxdxod.jpg",
                            ProductoId = 10
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6740),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20DELL%20INSPIRON%2015-3558%20%E2%80%93%20Intel%20Core%20i3%20Quinta%20Generaci%C3%B3n%20%E2%80%93%204GB%20RAM%20%E2%80%93%201TB%20HDD/Laptop_DELL_INSPIRON_15-3558_Intel_Core_i3_Quinta_Generaci%C3%B3n_4GB_RAM_1TB_HDD_13558dell36689_qgimk8.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816983/Sistema-Ventas/Laptops/Laptop DELL INSPIRON 15-3558 – Intel Core i3 Quinta Generación – 4GB RAM – 1TB HDD/Laptop_DELL_INSPIRON_15-3558_Intel_Core_i3_Quinta_Generación_4GB_RAM_1TB_HDD_13558dell36689_qgimk8.jpg",
                            ProductoId = 10
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6874),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20Dell%20Latitude%203350%20%E2%80%93%20Intel%20Core%20I5%20Quinta%20Generaci%C3%B3n/Laptop_Dell_Latitude_3350_Intel_Core_I5_Quinta_Generaci%C3%B3n_dell-latitude-3350-monsterlaptops_zcypyv.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816984/Sistema-Ventas/Laptops/Laptop Dell Latitude 3350 – Intel Core I5 Quinta Generación/Laptop_Dell_Latitude_3350_Intel_Core_I5_Quinta_Generación_dell-latitude-3350-monsterlaptops_zcypyv.jpg",
                            ProductoId = 11
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(6975),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20Dell%20Latitude%203350%20%E2%80%93%20Intel%20Core%20I5%20Quinta%20Generaci%C3%B3n/Laptop_Dell_Latitude_3350_Intel_Core_I5_Quinta_Generaci%C3%B3n_3dell-latitude-3350-monsterlaptops_yid0mm.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816984/Sistema-Ventas/Laptops/Laptop Dell Latitude 3350 – Intel Core I5 Quinta Generación/Laptop_Dell_Latitude_3350_Intel_Core_I5_Quinta_Generación_3dell-latitude-3350-monsterlaptops_yid0mm.jpg",
                            ProductoId = 11
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(7109),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20Dell%20Latitude%203350%20%E2%80%93%20Intel%20Core%20I5%20Quinta%20Generaci%C3%B3n/Laptop_Dell_Latitude_3350_Intel_Core_I5_Quinta_Generaci%C3%B3n_1dell-latitude-3350-monsterlaptops_j1aoqx.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816983/Sistema-Ventas/Laptops/Laptop Dell Latitude 3350 – Intel Core I5 Quinta Generación/Laptop_Dell_Latitude_3350_Intel_Core_I5_Quinta_Generación_1dell-latitude-3350-monsterlaptops_j1aoqx.jpg",
                            ProductoId = 11
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(7243),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20Dell%20Latitude%20E5450%20%E2%80%93%20i5%20Quinta%20Generaci%C3%B3n%20%E2%80%93%208GB%20RAM%20%E2%80%93%20500GB%20HDD/Laptop_Dell_Latitude_E5450_i5_Quinta_Generaci%C3%B3n_8GB_RAM_500GB_HDD_delle51267_wodunh.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816984/Sistema-Ventas/Laptops/Laptop Dell Latitude E5450 – i5 Quinta Generación – 8GB RAM – 500GB HDD/Laptop_Dell_Latitude_E5450_i5_Quinta_Generación_8GB_RAM_500GB_HDD_delle51267_wodunh.jpg",
                            ProductoId = 12
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(7382),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20Dell%20Latitude%20E5450%20%E2%80%93%20i5%20Quinta%20Generaci%C3%B3n%20%E2%80%93%208GB%20RAM%20%E2%80%93%20500GB%20HDD/Laptop_Dell_Latitude_E5450_i5_Quinta_Generaci%C3%B3n_8GB_RAM_500GB_HDD_0vnb125_hdadig.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816984/Sistema-Ventas/Laptops/Laptop Dell Latitude E5450 – i5 Quinta Generación – 8GB RAM – 500GB HDD/Laptop_Dell_Latitude_E5450_i5_Quinta_Generación_8GB_RAM_500GB_HDD_0vnb125_hdadig.jpg",
                            ProductoId = 12
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(7406),
                            FotoPublicId = "Sistema-Ventas/Celulares/Huawei%20Y7p/Huawei_Y7p_Precio-Huawei-Y7p-en-Costa-Rica_nfiokl.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816945/Sistema-Ventas/Celulares/Huawei Y7p/Huawei_Y7p_Precio-Huawei-Y7p-en-Costa-Rica_nfiokl.jpg",
                            ProductoId = 13
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(7421),
                            FotoPublicId = "Sistema-Ventas/Celulares/Huawei%20Y7p/Huawei_Y7p_Comprar-Huawei-Y7p-en-Costa-Rica_at8yeh.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816945/Sistema-Ventas/Celulares/Huawei Y7p/Huawei_Y7p_Comprar-Huawei-Y7p-en-Costa-Rica_at8yeh.jpg",
                            ProductoId = 13
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(7436),
                            FotoPublicId = "Sistema-Ventas/Celulares/Huawei%20Y7p/Huawei_Y7p_Huawei-Y7p-en-Costa-Rica-1_mawrci.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816944/Sistema-Ventas/Celulares/Huawei Y7p/Huawei_Y7p_Huawei-Y7p-en-Costa-Rica-1_mawrci.jpg",
                            ProductoId = 13
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(7568),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20Dell%20Ultrabook%20E7240%20%E2%80%93%2012GB%20Ram%20%E2%80%93%20Intel%20Core%20i5%20%E2%80%93%20128GB%20SSD%20%E2%80%93%20Teclado%20Iluminado/Laptop_Dell_Ultrabook_E7240_12GB_Ram_Intel_Core_i5_128GB_SSD_Teclado_Iluminado_delle72404433_tllnkp.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816984/Sistema-Ventas/Laptops/Laptop Dell Ultrabook E7240 – 12GB Ram – Intel Core i5 – 128GB SSD – Teclado Iluminado/Laptop_Dell_Ultrabook_E7240_12GB_Ram_Intel_Core_i5_128GB_SSD_Teclado_Iluminado_delle72404433_tllnkp.jpg",
                            ProductoId = 14
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(7704),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20Dell%20Ultrabook%20E7240%20%E2%80%93%2012GB%20Ram%20%E2%80%93%20Intel%20Core%20i5%20%E2%80%93%20128GB%20SSD%20%E2%80%93%20Teclado%20Iluminado/Laptop_Dell_Ultrabook_E7240_12GB_Ram_Intel_Core_i5_128GB_SSD_Teclado_Iluminado_2delle72404433_gkbrxs.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816984/Sistema-Ventas/Laptops/Laptop Dell Ultrabook E7240 – 12GB Ram – Intel Core i5 – 128GB SSD – Teclado Iluminado/Laptop_Dell_Ultrabook_E7240_12GB_Ram_Intel_Core_i5_128GB_SSD_Teclado_Iluminado_2delle72404433_gkbrxs.jpg",
                            ProductoId = 14
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(7834),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20Dell%20Ultrabook%20E7240%20%E2%80%93%2012GB%20Ram%20%E2%80%93%20Intel%20Core%20i5%20%E2%80%93%20128GB%20SSD%20%E2%80%93%20Teclado%20Iluminado/Laptop_Dell_Ultrabook_E7240_12GB_Ram_Intel_Core_i5_128GB_SSD_Teclado_Iluminado_1delle72404433_ie14cu.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816984/Sistema-Ventas/Laptops/Laptop Dell Ultrabook E7240 – 12GB Ram – Intel Core i5 – 128GB SSD – Teclado Iluminado/Laptop_Dell_Ultrabook_E7240_12GB_Ram_Intel_Core_i5_128GB_SSD_Teclado_Iluminado_1delle72404433_ie14cu.jpg",
                            ProductoId = 14
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8003),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20HP%2015-ba051wm%20%E2%80%93%20Pantalla%20Touch%20%E2%80%93%20Quad-Core%20A10-9600P%20%E2%80%93%208GB%20RAM%20%E2%80%93%201TB%20HDD%20%E2%80%93%20Teclado%20Num%C3%A9rico/Laptop_HP_15-ba051wm_Pantalla_Touch_Quad-Core_A10-9600P_8GB_RAM_1TB_HDD_Teclado_Num%C3%A9rico_d1bcb5c0-8ba3-4703-_do4ilh.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816984/Sistema-Ventas/Laptops/Laptop HP 15-ba051wm – Pantalla Touch – Quad-Core A10-9600P – 8GB RAM – 1TB HDD – Teclado Numérico/Laptop_HP_15-ba051wm_Pantalla_Touch_Quad-Core_A10-9600P_8GB_RAM_1TB_HDD_Teclado_Numérico_d1bcb5c0-8ba3-4703-_do4ilh.jpg",
                            ProductoId = 15
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8027),
                            FotoPublicId = "Sistema-Ventas/Celulares/iPhone%2011%20%28128GB%29/iPhone_11_128GB_iPhone-11-precio-Costa-Rica_efrulu.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816946/Sistema-Ventas/Celulares/iPhone 11 %28128GB%29/iPhone_11_128GB_iPhone-11-precio-Costa-Rica_efrulu.jpg",
                            ProductoId = 16
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8046),
                            FotoPublicId = "Sistema-Ventas/Celulares/iPhone%2011%20%28128GB%29/iPhone_11_128GB_iphone-11-de-venta-en-Costa-Rica_gg3uib.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816946/Sistema-Ventas/Celulares/iPhone 11 %28128GB%29/iPhone_11_128GB_iphone-11-de-venta-en-Costa-Rica_gg3uib.jpg",
                            ProductoId = 16
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8063),
                            FotoPublicId = "Sistema-Ventas/Celulares/iPhone%2011%20%28128GB%29/iPhone_11_128GB_iPhone-11-en-costa-Rica_ooxbv5.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816945/Sistema-Ventas/Celulares/iPhone 11 %28128GB%29/iPhone_11_128GB_iPhone-11-en-costa-Rica_ooxbv5.jpg",
                            ProductoId = 16
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8079),
                            FotoPublicId = "Sistema-Ventas/Celulares/iPhone%208%20Plus%2064GB/iPhone_8_Plus_64GB_precio-iphone-8-plus-en-costa-rica_pl8wtz.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816946/Sistema-Ventas/Celulares/iPhone 8 Plus 64GB/iPhone_8_Plus_64GB_precio-iphone-8-plus-en-costa-rica_pl8wtz.jpg",
                            ProductoId = 17
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8095),
                            FotoPublicId = "Sistema-Ventas/Celulares/iPhone%208%20Plus%2064GB/iPhone_8_Plus_64GB_comprar-iphone-8-plus-en-costa-rica_kyu29s.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816945/Sistema-Ventas/Celulares/iPhone 8 Plus 64GB/iPhone_8_Plus_64GB_comprar-iphone-8-plus-en-costa-rica_kyu29s.jpg",
                            ProductoId = 17
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8111),
                            FotoPublicId = "Sistema-Ventas/Celulares/iPhone%208%20Plus%2064GB/iPhone_8_Plus_64GB_iphone-8-plus-en-costa-rica_h2hwur.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816945/Sistema-Ventas/Celulares/iPhone 8 Plus 64GB/iPhone_8_Plus_64GB_iphone-8-plus-en-costa-rica_h2hwur.jpg",
                            ProductoId = 17
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8346),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20HP%2015-f387wm%20%E2%80%93%20AMD%20A8-7410%20%E2%80%93%20500GB%20HDD%20%E2%80%93%204GB%20RAM%20%E2%80%93%20Radeon%20R5%20%E2%80%93%20Pantalla%20T%C3%A1ctil%20%E2%80%93%20Teclado%20Num%C3%A9rico/Laptop_HP_15-f387wm_AMD_A8-7410_500GB_HDD_4GB_RAM_Radeon_R5_Pantalla_T%C3%A1ctil_Teclado_Num%C3%A9rico_b62ed24wmr_mzyzt4.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816985/Sistema-Ventas/Laptops/Laptop HP 15-f387wm – AMD A8-7410 – 500GB HDD – 4GB RAM – Radeon R5 – Pantalla Táctil – Teclado Numérico/Laptop_HP_15-f387wm_AMD_A8-7410_500GB_HDD_4GB_RAM_Radeon_R5_Pantalla_Táctil_Teclado_Numérico_b62ed24wmr_mzyzt4.jpg",
                            ProductoId = 18
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8577),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20HP%2015-f387wm%20%E2%80%93%20AMD%20A8-7410%20%E2%80%93%20500GB%20HDD%20%E2%80%93%204GB%20RAM%20%E2%80%93%20Radeon%20R5%20%E2%80%93%20Pantalla%20T%C3%A1ctil%20%E2%80%93%20Teclado%20Num%C3%A9rico/Laptop_HP_15-f387wm_AMD_A8-7410_500GB_HDD_4GB_RAM_Radeon_R5_Pantalla_T%C3%A1ctil_Teclado_Num%C3%A9rico_b3b5615cwmg_wnhba0.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816985/Sistema-Ventas/Laptops/Laptop HP 15-f387wm – AMD A8-7410 – 500GB HDD – 4GB RAM – Radeon R5 – Pantalla Táctil – Teclado Numérico/Laptop_HP_15-f387wm_AMD_A8-7410_500GB_HDD_4GB_RAM_Radeon_R5_Pantalla_Táctil_Teclado_Numérico_b3b5615cwmg_wnhba0.jpg",
                            ProductoId = 18
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8759),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20HP%2015-f387wm%20%E2%80%93%20AMD%20A8-7410%20%E2%80%93%20500GB%20HDD%20%E2%80%93%204GB%20RAM%20%E2%80%93%20Radeon%20R5%20%E2%80%93%20Pantalla%20T%C3%A1ctil%20%E2%80%93%20Teclado%20Num%C3%A9rico/Laptop_HP_15-f387wm_AMD_A8-7410_500GB_HDD_4GB_RAM_Radeon_R5_Pantalla_T%C3%A1ctil_Teclado_Num%C3%A9rico_a8-1wemk_psrtud.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816985/Sistema-Ventas/Laptops/Laptop HP 15-f387wm – AMD A8-7410 – 500GB HDD – 4GB RAM – Radeon R5 – Pantalla Táctil – Teclado Numérico/Laptop_HP_15-f387wm_AMD_A8-7410_500GB_HDD_4GB_RAM_Radeon_R5_Pantalla_Táctil_Teclado_Numérico_a8-1wemk_psrtud.jpg",
                            ProductoId = 18
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8879),
                            FotoPublicId = "Sistema-Ventas/Laptops/Laptop%20HP%2015-f387wm%20%E2%80%93%20AMD%20A8-7410%20%E2%80%93%20500GB%20HDD%20%E2%80%93%204GB%20RAM%20%E2%80%93%20Radeon%20R5%20%E2%80%93%20Pantalla%20T%C3%A1ctil%20%E2%80%93%20Teclado%20Num%C3%A9rico/Laptop_HP_15-f387wm_AMD_A8-7410_500GB_HDD_4GB_RAM_Radeon_R5_Pantalla_T%C3%A1ctil_Teclado_Num%C3%A9rico_2da6aa5wmol_jzvmjy.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816985/Sistema-Ventas/Laptops/Laptop HP 15-f387wm – AMD A8-7410 – 500GB HDD – 4GB RAM – Radeon R5 – Pantalla Táctil – Teclado Numérico/Laptop_HP_15-f387wm_AMD_A8-7410_500GB_HDD_4GB_RAM_Radeon_R5_Pantalla_Táctil_Teclado_Numérico_2da6aa5wmol_jzvmjy.jpg",
                            ProductoId = 18
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8894),
                            FotoPublicId = "Sistema-Ventas/Celulares/LG%20Aristo%205/LG_Aristo_5_LG-Aristo-5-Silver-frontimage_cvqajy.png",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816947/Sistema-Ventas/Celulares/LG Aristo 5/LG_Aristo_5_LG-Aristo-5-Silver-frontimage_cvqajy.png",
                            ProductoId = 19
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8905),
                            FotoPublicId = "Sistema-Ventas/Celulares/LG%20Aristo%205/LG_Aristo_5_LG-Aristo-5_qgxdwn.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816947/Sistema-Ventas/Celulares/LG Aristo 5/LG_Aristo_5_LG-Aristo-5_qgxdwn.jpg",
                            ProductoId = 19
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8916),
                            FotoPublicId = "Sistema-Ventas/Celulares/Samsung%20Galaxy%20A11/Samsung_Galaxy_A11_Samsung-Galaxy-A11-en-Costa-Rica_ag1ltk.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816947/Sistema-Ventas/Celulares/Samsung Galaxy A11/Samsung_Galaxy_A11_Samsung-Galaxy-A11-en-Costa-Rica_ag1ltk.jpg",
                            ProductoId = 20
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8926),
                            FotoPublicId = "Sistema-Ventas/Celulares/Samsung%20Galaxy%20A11/Samsung_Galaxy_A11_Venta-Samsung-Galaxy-A11-en-Costa-Rica_da7fjh.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816947/Sistema-Ventas/Celulares/Samsung Galaxy A11/Samsung_Galaxy_A11_Venta-Samsung-Galaxy-A11-en-Costa-Rica_da7fjh.jpg",
                            ProductoId = 20
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8936),
                            FotoPublicId = "Sistema-Ventas/Celulares/Samsung%20Galaxy%20A11/Samsung_Galaxy_A11_Comprar-Samsung-Galaxy-A11-en-Costa-Rica_wdx6c3.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816947/Sistema-Ventas/Celulares/Samsung Galaxy A11/Samsung_Galaxy_A11_Comprar-Samsung-Galaxy-A11-en-Costa-Rica_wdx6c3.jpg",
                            ProductoId = 20
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 551, DateTimeKind.Local).AddTicks(8947),
                            FotoPublicId = "Sistema-Ventas/Celulares/Samsung%20Galaxy%20A11/Samsung_Galaxy_A11_Precio-Samsung-Galaxy-A11-en-Costa-Rica_x9xdds.jpg",
                            FotoUrl = "https://res.cloudinary.com/alexander-damaso-26857/image/upload/v1595816947/Sistema-Ventas/Celulares/Samsung Galaxy A11/Samsung_Galaxy_A11_Precio-Samsung-Galaxy-A11-en-Costa-Rica_x9xdds.jpg",
                            ProductoId = 20
                        });
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteGuid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.DetalleCarrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarritoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleCarritos");
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarritoId")
                        .IsUnique();

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId")
                        .IsUnique();

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Usuario.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Administradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 540, DateTimeKind.Local).AddTicks(3343),
                            Email = "ADMIN@GMAIL.COM",
                            Estado = true,
                            PasswordHash = new byte[] { 179, 168, 87, 201, 124, 215, 81, 53, 38, 10, 111, 241, 243, 29, 228, 135, 151, 140, 87, 25, 27, 162, 63, 145, 202, 173, 43, 146, 20, 5, 63, 65 },
                            RolId = 1,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 540, DateTimeKind.Local).AddTicks(2657),
                            Username = "ADMIN01"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 540, DateTimeKind.Local).AddTicks(6319),
                            Email = "ORGANIZADOR@GMAIL.COM",
                            Estado = true,
                            PasswordHash = new byte[] { 21, 225, 68, 250, 22, 151, 169, 169, 217, 51, 91, 118, 133, 88, 207, 208, 50, 24, 183, 173, 239, 120, 113, 147, 79, 74, 155, 228, 252, 69, 160, 81 },
                            RolId = 2,
                            UpdatedAt = new DateTime(2020, 8, 5, 16, 25, 24, 540, DateTimeKind.Local).AddTicks(6277),
                            Username = "ORGANIZADOR"
                        });
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Usuario.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNac")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Usuario.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso máximo del sistema.",
                            Estado = true,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Acceso a las ordenes del sistema.",
                            Estado = true,
                            Nombre = "Organizador"
                        });
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Almacen.Producto", b =>
                {
                    b.HasOne("Sistema.Api.Entidades.Almacen.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Api.Entidades.Almacen.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Almacen.ProductoFoto", b =>
                {
                    b.HasOne("Sistema.Api.Entidades.Almacen.Producto", null)
                        .WithMany("Fotos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.Carrito", b =>
                {
                    b.HasOne("Sistema.Api.Entidades.Usuario.Cliente", "Cliente")
                        .WithOne("Carrito")
                        .HasForeignKey("Sistema.Api.Entidades.Ordenes.Carrito", "ClienteId");
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.DetalleCarrito", b =>
                {
                    b.HasOne("Sistema.Api.Entidades.Ordenes.Carrito", "Carrito")
                        .WithMany("Detalles")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Api.Entidades.Almacen.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.Orden", b =>
                {
                    b.HasOne("Sistema.Api.Entidades.Ordenes.Carrito", "Carrito")
                        .WithOne("Orden")
                        .HasForeignKey("Sistema.Api.Entidades.Ordenes.Orden", "CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Api.Entidades.Usuario.Cliente", null)
                        .WithOne("Orden")
                        .HasForeignKey("Sistema.Api.Entidades.Ordenes.Orden", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.Pago", b =>
                {
                    b.HasOne("Sistema.Api.Entidades.Ordenes.Orden", "Orden")
                        .WithOne("Pago")
                        .HasForeignKey("Sistema.Api.Entidades.Ordenes.Pago", "OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Ordenes.Pedido", b =>
                {
                    b.HasOne("Sistema.Api.Entidades.Ordenes.Orden", "Orden")
                        .WithOne("Pedido")
                        .HasForeignKey("Sistema.Api.Entidades.Ordenes.Pedido", "OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema.Api.Entidades.Usuario.Administrador", b =>
                {
                    b.HasOne("Sistema.Api.Entidades.Usuario.Rol", "Rol")
                        .WithMany("Administradores")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
